version: '3.1'

services:

  mongo:
    image: mongodb/mongodb-community-server
    restart: always
    container_name: mongo-server
    environment:
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Password2023!

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8088:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: Password2023!
      ME_CONFIG_MONGODB_URL: mongodb://admin:Password2023!@mongo:27017/

